install ctags
install gawk
install git
install grc
install highlight
install imagemagick
install openssl
install qt
install redis
install the_silver_searcher
install tree
install vim
install zsh-completions
