" Use space as leader
let mapleader=" "
let &t_Co=256

syntax on

if filereadable(expand("~/.vimrc.bundles"))
  source ~/.vimrc.bundles
endif

" Force reload
filetype off
filetype plugin indent on

runtime macros/matchit.vim

augroup vimrcEx
  autocmd!

  " When editing a file, always jump to the last known cursor position.
  " Don't do it for commit messages, when the position is invalid, or when
  " inside an event handler (happens when dropping a file on gvim).
  autocmd BufReadPost *
    \ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif
augroup END

" Color scheme
set background=dark
let g:solarized_termcolors=256
colorscheme solarized
call togglebg#map("cb")

"-----------------------
" SETTINGS
"-----------------------

" Set my font
set guifont=Monaco:h14

" Disable mouse
set mouse=""

" Remove right side bar in mac vim
set guioptions-=r
set guioptions-=L

" Sets the block cursor in all modes
set guicursor=a:block-Cursor

" Use system clipboard on vim
set clipboard=unnamed

" Show branch in status line
set laststatus=2
set statusline=%t       "tail of the filename
set statusline+=[%{strlen(&fenc)?&fenc:'none'}, "file encoding
set statusline+=%{&ff}] "file format
set statusline+=%h      "help file flag
set statusline+=%m      "modified flag
set statusline+=%r      "read only flag
set statusline+=%y      "filetype
set statusline+=%=      "left/right separator
set statusline+=%c,     "cursor column
set statusline+=%l/%L   "cursor line/total lines
set statusline+=\ %P    "percent through file
set statusline+=\ %{'('.fugitive#head(7).')'} "git branch

" Backup stuff
set nobackup
set nowritebackup
set noswapfile
set noundofile

" Automatically write before running commands
set autowrite

" Highlights current line and column
set cursorcolumn
set cursorline

" CTags settings
set tags=./tags;

set tabstop=2
set shiftwidth=2
set expandtab
set autoindent
set smarttab
set nowrap
set backspace=indent,eol,start
set autoindent
set copyindent
set shiftround
set ignorecase
set smartcase
set hlsearch
set undolevels=1000
set title
set visualbell
set noerrorbells
set list

set listchars=tab:--,trail:.,nbsp:.
set pastetoggle=<C-p>

set relativenumber
set number

"-----------------------
" NORMAL MODE MAPPINGS
"-----------------------

" ctags
nnoremap fd <C-]>

" Remove all ruby comments
nnoremap rc :g/^ *#.*/d<CR>

" Remove search highlight
nmap <silent> ,. :nohlsearch<CR>

" Do not jump over wrapped lines
nnoremap j gj
nnoremap k gk

" Easy window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Stupid 'murichans
map º [
map ´ ]

" RSpec.vim mappings
map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif

" Bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR><CR>

" Bind <C-f> to grep shortcut
command! -nargs=+ -complete=file -bar Ag silent! grep! <args>|cwindow|redraw!
nnoremap <C-f> :Ag<SPACE>

nnoremap <C-n> :call NumberToggle()<cr>

" Remap buffer closing
nnoremap <silent> <Leader>q <Esc>:bw<cr>

" Open this file
map vimrc :tabe ~/.vim/vimrc<CR>

" Open bash profile
map sh :tabe ~/.bash_profile

" Change all double to single quotes
map <silent> sq <esc>:%s/"\([^"]*\)"/'\1'/g<CR>

" Work on coachme
map <silent> cm :! cd $HOME/Code/Ruby/GroupBuddies/coachme<cr>:e app/<cr>

" Ruby test
map <Leader>r <Plug>RubyTestRun
map <Leader>R <Plug>RubyFileRun

" NERDTree
map <silent> <Leader>o :NERDTreeToggle<CR>

" Indent complete file
map <Leader>i gg=G

"-----------------------
" INSERT MODE MAPPINGS
"-----------------------
" Tab completion
" will insert tab at beginning of line,
" will use completion if not at beginning
set wildmode=list:longest,list:full
set complete=.,w,t
function! InsertTabWrapper()
    let col = col('.') - 1
    if !col || getline('.')[col - 1] !~ '\k'
        return "\<tab>"
    else
        return "\<c-p>"
    endif
endfunction
inoremap <Tab> <c-r>=InsertTabWrapper()<cr>

"-----------------------
" COMMAND MODE MAPPINGS
"-----------------------

" When you forget to sudo a file
cmap w!! w !sudo tee % >/dev/null

"-----------------------
" VISUAL MODE MAPPINGS
"-----------------------

" Visual block git blame
vmap <Leader>b :! git blame <C-R>=expand("%:p") <CR> \| sed -n <C-R>=line("'<") <CR>,<C-R>=line("'>") <CR>p <CR>

" Visual mode duplicate below
vmap D y'>p<S-O><Esc>


"-----------------------
" LETS
"-----------------------

" Ack.vim configs
let g:ackprg="/usr/local/bin/ack -H --nogroup --column --nopager --nocolor"

" Fuzzy finder: ignore stuff that can't be opened, and generated files
let g:fuzzy_ignore = "*.png;*.PNG;*.JPG;*.jpg;*.GIF;*.gif;vendor/**;coverage/**;tmp/**;rdoc/**"

"-----------------------
" AUTOCOMMANDS
"-----------------------

" Remove trailing whitespaces
autocmd BufWritePre <buffer> :%s/\s\+$//e

" Disable auto comment insertion
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Enable rvm
" autocmd BufEnter * Rvm

" NERDTree when no files
autocmd vimenter * if !argc() | NERDTree | endif

" Delete trailing whitespace
autocmd BufWritePre * :%s/\s\+$//e

"-----------------------
" FUNCTIONS
"-----------------------

" Line number settings
function! NumberToggle()
  if(&relativenumber == 1)
    set norelativenumber
  else
    set relativenumber
  endif
endfunc

"-----------------------
" OTHER
"-----------------------

" Highlight the status line
highlight StatusLine ctermbg=black

" Open rails routes file
command! Rroutes :e config/routes.rb

" Open rails factories file
command! Rfactories :e spec/factories.rb

" EXPERIMENT
inoremap  <Up>     <NOP>
inoremap  <Down>   <NOP>
inoremap  <Left>   <NOP>
inoremap  <Right>  <NOP>
noremap   <Up>     <NOP>
noremap   <Down>   <NOP>
noremap   <Left>   <NOP>
noremap   <Right>  <NOP>

noremap   v     <NOP>
noremap   V   <NOP>
