source ~/.vim/bundles.vim
lua dofile(os.getenv("HOME") .. "/.vim/lua/colors.lua")
source ~/.vim/functions.vim
source ~/.vim/config.vim
source ~/.vim/autocomands.vim
source ~/.vim/plugins.vim
source ~/.vim/shortcuts.vim
lua dofile(os.getenv("HOME") .. "/.vim/lua/plugins.lua")
source ~/.vim/statusline.vim
